Repository mira-amm/mira-amm-web, pull requests merged in 2025-03, with the labels that each got.

#300 Fix/liquidity page UI
  src/components/common/Info/Info.module.css
  src/components/pages/add-liquidity-page/components/AddLiquidity/AddLiquidity.module.css
  src/components/pages/view-position-page/components/PositionView/PositionView.tsx
  src/hooks/useRemoveLiquidity.ts
Labels: mira-bug-bounty

#311 ci: set up observability solution
  .gitignore
  app/global-error.tsx
  instrumentation.ts
  next.config.mjs
  package.json
  pnpm-lock.yaml
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
Labels: ☁️ DevOps/Infrastructure

#312 chore(config/editor): create file
  .editorconfig
Labels: ☁️ DevOps/Infrastructure

#329 fix(ui/liquidity): closing remove liquidity success dialog redirects to `/liquidity`
  apps/web-e2e/src/index.spec.ts
  src/components/pages/view-position-page/components/PositionView/PositionView.tsx
Labels: ✨ Front-End Development

#318 Fix/transactions tab
  package-lock.json
  src/components/common/TransactionsHistory/TransactionsHistory.tsx
  src/hooks/useWalletTransactions.ts
  src/utils/constants.ts
Labels: mira-bug-bounty
